apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{ template "fullname" . }}'
  annotations:
spec:
  rules:
  - host: "{{ .Values.ingress.subdomain }}.||&domain||"
    http:
      paths:
      - path: "{{ .Values.ingress.path }}"
        backend:
          serviceName: '{{ template "fullname" . }}'
          servicePort: "{{ .Values.service.externalPort }}"
